__version__ = "1.0.0"
__codename__ = "coca"
__version_info__ = (1, 0, 0, "final")

from .segmentation.segmentor import Segmentor
from .dictionary.dictionary import Dictionary, UserDictionary, DictionaryManager
from .dictionary.dictionary_version import DictionaryVersion, DictionaryVersionManager, VersionedDictionary, VersionedUserDictionary
from .dictionary.domain_dictionary import DomainDictionary, DomainDictionaryManager
from .dictionary.network_dictionary import NetworkDictionary
from .dictionary.incremental_dictionary import (
    DictionaryUpdateEvent,
    DictionaryObserver,
    IncrementalDictionary,
    IncrementalUserDictionary,
    DictionaryUpdateManager,
    HotUpdateDictionaryManager
)
from .dictionary.stopwords import StopWords
from .text_analysis.keyword_extractor import KeywordExtractor
from .text_analysis.similarity import Similarity
from .dictionary.trie import Trie
from .core.benchmark import PerformanceBenchmark, BenchmarkResult, measure_time
from .core.batch_processor import BatchProcessor
from .core.traditional_chinese import TraditionalChineseConverter, TraditionalChineseDictionary
from .segmentation.hmm import HMMSegmentor, train_from_file
from .segmentation.ngram import NGramModel, BigramModel, TrigramModel
from .segmentation.crf import CRFModel, CRFSegmentor, CRFFeatureTemplate
from .segmentation.perceptron import StructuredPerceptron, PerceptronSegmentor, PerceptronFeatureTemplate
from .segmentation.lattice import Lattice, LatticeEdge, LatticeNode, LatticeBuilder, LatticeSegmentor, PathScorer
from .segmentation.ambiguity import AmbiguityType, AmbiguityRegion, AmbiguityResult, AmbiguityDetector
from .segmentation.new_word_detector import NewWordDetector, MutualInformation, EntropyCalculator
from .parsing.pos_tagger import POS_TAGS, DEFAULT_TAGS, HMMPOSTagger, CRFPOSTagger, train_pos_from_file
from .ner.ner import (
    NER_ENTITY_TYPES,
    NER_TAGS,
    DEFAULT_NER_TAGS,
    Entity,
    NERFeatureTemplate,
    CRFNERModel,
    NERRecognizer,
    create_sample_ner_corpus,
    train_ner_from_file,
    NestedEntity,
    EntityHierarchy,
    NESTING_RULES,
    NestedNERRecognizer,
    create_nested_ner_corpus,
)
from .ner.entity_linker import (
    KnowledgeEntity,
    LinkedEntity,
    KnowledgeBase,
    EntityNormalizer,
    EntityLinker,
    create_sample_knowledge_base,
    create_sample_normalizer,
)
from .parsing.dependency_parser import (
    Transition,
    DEPENDENCY_RELATIONS,
    DEFAULT_RELATIONS,
    DependencyArc,
    DependencyNode,
    DependencyTree,
    ParserState,
    ArcEagerOracle,
    DependencyFeatureExtractor,
    DependencyParser,
    create_sample_dependency_corpus,
    train_dependency_parser_from_file,
)
from .parsing.constituent_parser import (
    CONSTITUENT_LABELS,
    POS_LABELS,
    DEFAULT_NON_TERMINALS,
    DEFAULT_TERMINALS,
    GrammarRule,
    ConstituentNode,
    ConstituentTree,
    PCFG,
    CKYParser,
    ConstituentParser,
    create_sample_constituent_trees,
    train_constituent_parser_from_file,
)
from .segmentation.hybrid import (
    HybridStrategy,
    SegmenterType,
    SegmenterResult,
    HybridConfig,
    FusionContext,
    FusionStrategy,
    VoteFusionStrategy,
    WeightedFusionStrategy,
    CascadeFusionStrategy,
    ConfidenceFusionStrategy,
    FusionStrategyFactory,
    ConfidenceEstimator,
    CoverageConfidenceEstimator,
    WordQualityConfidenceEstimator,
    SegmentationQualityConfidenceEstimator,
    CompositeConfidenceEstimator,
    TextClassifier,
    StrategySelector,
    DeepLearningInterface,
    HybridSegmentor,
)
from .dictionary.scel_parser import ScelParser, ScelWord, ScelMetadata, ScelBatchParser
from .dictionary.sogou_dict import ScelConverter, SogouDictionary, SogouDictionaryManager
from .managers.managers import (
    DictionaryService,
    StopWordsManager,
    KeywordExtractorManager,
    SimilarityManager,
    MLSegmentorManager,
    LatticeSegmentorManager,
    AmbiguityDetectorManager,
    NewWordDetectorManager,
    HybridSegmentorManager,
)
from .dictionary.thesaurus import (
    WordRelation,
    CATEGORY_NAMES,
    SUBCATEGORY_NAMES,
    ThesaurusEntry,
    SemanticCategory,
    Thesaurus,
    ThesaurusManager,
)
from .ner.person_name import (
    Gender,
    SurnameType,
    Surname,
    NameChar,
    PersonName,
    NAME_CHAR_CATEGORIES,
    PersonNameDictionary,
    PersonNameManager,
)
from .ner.location import (
    AdminLevel,
    Location,
    LocationDatabase,
    LocationManager,
)
from .ner.organization import (
    OrgType,
    EnterpriseType,
    SchoolType,
    HospitalType,
    GovType,
    ENTERPRISE_SUFFIXES,
    SCHOOL_SUFFIXES,
    HOSPITAL_SUFFIXES,
    GOV_SUFFIXES,
    Organization,
    Enterprise,
    School,
    Hospital,
    Government,
    OrganizationDatabase,
    OrganizationManager,
)
from .dictionary.terminology import (
    TermDomain,
    DOMAIN_SCEL_MAPPING,
    Term,
    TerminologyDatabase,
    TerminologyManager,
)
from .corpus.corpus_builder import CorpusBuilder, CorpusManager
from .corpus.corpus_annotator import CorpusAnnotator, AnnotationManager, ActiveLearningStrategy, AnnotationQualityEvaluator
from .deep_learning import Framework, FrameworkType, get_framework, PyTorchBackend, TensorFlowBackend, BiLSTMCRF
from .pipeline.pipeline import (
    StringStore, Doc, Span, Token as PipelineToken,
    PipelineComponent, ConditionalBranch, Pipeline,
    ComponentRegistry, PipelineConfig, ConfigSchema, FreezableParams,
    ModelVersion, ModelLifecycle, LRUCache, ModelCache,
    APIServer, RPCServer, RPCClient,
    AsyncPipeline, AsyncTaskManager, StreamProcessor, ProgressCallback,
    Plugin, PluginManager, PluginDependency
)
from .core.performance import (
    ObjectPool, PoolContext,
    BatchProcessor as PerformanceBatchProcessor,
    MemoryPool, MemoryBlock,
    DelayedGC,
    ThreadPoolExecutor as NLPThreadPoolExecutor,
    ParallelTokenizer,
    ProcessPoolExecutor as NLPProcessPoolExecutor,
    GPUInterface,
    BatchInference,
    MixedPrecisionInference,
    TensorRTInterface,
    MemoryMappedFile,
    DictionaryCompressor,
    LRUResultCache,
    PerformanceMonitor,
    OptimizationSuite,
    Metric,
    DistributedTask,
    SimpleTaskScheduler
)
from .enterprise.enterprise import (
    LogLevel,
    LogFormat,
    StructuredLogRecord,
    ConsoleLogHandler,
    FileLogHandler,
    TimeRotatingFileLogHandler,
    MemoryLogHandler,
    LevelFilter,
    KeywordFilter,
    ModuleFilter,
    Logger,
    LogManager,
    get_logger,
    HealthStatus,
    HealthCheck,
    MemoryHealthCheck,
    DiskHealthCheck,
    HealthChecker,
    MetricType,
    PrometheusMetric,
    PrometheusCounter,
    PrometheusGauge,
    PrometheusRegistry,
    generate_dockerfile_content,
    generate_k8s_deployment_content,
    generate_k8s_service_content,
    generate_k8s_ingress_content,
    CircuitState,
    RateLimitState,
    TokenBucket,
    SlidingWindow,
    CircuitBreaker,
    TokenType,
    Permission,
    Token as EnterpriseToken,
    AuthContext,
    Authenticator,
    Authorizer,
    ConfigEvent,
    ConfigWatch,
    InMemoryConfigStore,
    FileConfigStore,
    ConfigManager,
    DeploymentState,
    TrafficRule,
    DeploymentVersion,
    CanaryDeployer,
    BackupType,
    ClusterNode,
    FailoverStrategy,
    DataBackupManager,
    FailoverController,
)

__all__ = [
    "Segmentor",
    "Dictionary",
    "UserDictionary",
    "DomainDictionary",
    "DomainDictionaryManager",
    "NetworkDictionary",
    "DictionaryManager",
    "DictionaryVersion",
    "DictionaryVersionManager",
    "VersionedDictionary",
    "VersionedUserDictionary",
    "DictionaryUpdateEvent",
    "DictionaryObserver",
    "IncrementalDictionary",
    "IncrementalUserDictionary",
    "DictionaryUpdateManager",
    "HotUpdateDictionaryManager",
    "StopWords",
    "KeywordExtractor",
    "Similarity",
    "Trie",
    "PerformanceBenchmark",
    "BenchmarkResult",
    "measure_time",
    "BatchProcessor",
    "HMMSegmentor",
    "train_from_file",
    "NGramModel",
    "BigramModel",
    "TrigramModel",
    "CRFModel",
    "CRFSegmentor",
    "CRFFeatureTemplate",
    "StructuredPerceptron",
    "PerceptronSegmentor",
    "PerceptronFeatureTemplate",
    "Lattice",
    "LatticeEdge",
    "LatticeNode",
    "LatticeBuilder",
    "LatticeSegmentor",
    "PathScorer",
    "AmbiguityType",
    "AmbiguityRegion",
    "AmbiguityResult",
    "AmbiguityDetector",
    "NewWordDetector",
    "MutualInformation",
    "EntropyCalculator",
    "POS_TAGS",
    "DEFAULT_TAGS",
    "HMMPOSTagger",
    "CRFPOSTagger",
    "train_pos_from_file",
    "NER_ENTITY_TYPES",
    "NER_TAGS",
    "DEFAULT_NER_TAGS",
    "Entity",
    "NERFeatureTemplate",
    "CRFNERModel",
    "NERRecognizer",
    "create_sample_ner_corpus",
    "train_ner_from_file",
    "NestedEntity",
    "EntityHierarchy",
    "NESTING_RULES",
    "NestedNERRecognizer",
    "create_nested_ner_corpus",
    "KnowledgeEntity",
    "LinkedEntity",
    "KnowledgeBase",
    "EntityNormalizer",
    "EntityLinker",
    "create_sample_knowledge_base",
    "create_sample_normalizer",
    "Transition",
    "DEPENDENCY_RELATIONS",
    "DEFAULT_RELATIONS",
    "DependencyArc",
    "DependencyNode",
    "DependencyTree",
    "ParserState",
    "ArcEagerOracle",
    "DependencyFeatureExtractor",
    "DependencyParser",
    "create_sample_dependency_corpus",
    "train_dependency_parser_from_file",
    "CONSTITUENT_LABELS",
    "POS_LABELS",
    "DEFAULT_NON_TERMINALS",
    "DEFAULT_TERMINALS",
    "GrammarRule",
    "ConstituentNode",
    "ConstituentTree",
    "PCFG",
    "CKYParser",
    "ConstituentParser",
    "create_sample_constituent_trees",
    "train_constituent_parser_from_file",
    "HybridStrategy",
    "SegmenterType",
    "SegmenterResult",
    "HybridConfig",
    "FusionContext",
    "FusionStrategy",
    "VoteFusionStrategy",
    "WeightedFusionStrategy",
    "CascadeFusionStrategy",

    "ConfidenceFusionStrategy",
    "FusionStrategyFactory",
    "ConfidenceEstimator",
    "CoverageConfidenceEstimator",
    "WordQualityConfidenceEstimator",
    "SegmentationQualityConfidenceEstimator",
    "CompositeConfidenceEstimator",
    "TextClassifier",
    "StrategySelector",
    "DeepLearningInterface",
    "HybridSegmentor",
    "ScelParser",
    "ScelWord",
    "ScelMetadata",
    "ScelBatchParser",
    "ScelConverter",
    "SogouDictionary",
    "SogouDictionaryManager",
    "DictionaryService",
    "StopWordsManager",
    "KeywordExtractorManager",
    "SimilarityManager",
    "MLSegmentorManager",
    "LatticeSegmentorManager",
    "AmbiguityDetectorManager",
    "NewWordDetectorManager",
    "HybridSegmentorManager",
    "WordRelation",
    "CATEGORY_NAMES",
    "SUBCATEGORY_NAMES",
    "ThesaurusEntry",
    "SemanticCategory",
    "Thesaurus",
    "ThesaurusManager",
    "Gender",
    "SurnameType",
    "Surname",
    "NameChar",
    "PersonName",
    "NAME_CHAR_CATEGORIES",
    "PersonNameDictionary",
    "PersonNameManager",
    "AdminLevel",
    "Location",
    "LocationDatabase",
    "LocationManager",
    "OrgType",
    "EnterpriseType",
    "SchoolType",
    "HospitalType",
    "GovType",
    "ENTERPRISE_SUFFIXES",
    "SCHOOL_SUFFIXES",
    "HOSPITAL_SUFFIXES",
    "GOV_SUFFIXES",
    "Organization",
    "Enterprise",
    "School",
    "Hospital",
    "Government",
    "OrganizationDatabase",
    "OrganizationManager",
    "TermDomain",
    "DOMAIN_SCEL_MAPPING",
    "Term",
    "TerminologyDatabase",
    "TerminologyManager",
    "CorpusBuilder",
    "CorpusManager",
    "CorpusAnnotator",
    "AnnotationManager",
    "ActiveLearningStrategy",
    "AnnotationQualityEvaluator",
    "Framework",
    "FrameworkType",
    "get_framework",
    "PyTorchBackend",
    "TensorFlowBackend",
    "BiLSTMCRF",
    # 架构重构 (步骤51-65)
    "StringStore",
    "Doc",
    "Span",
    "PipelineToken",
    "PipelineComponent",
    "ConditionalBranch",
    "Pipeline",
    "ComponentRegistry",
    "PipelineConfig",
    "ConfigSchema",
    "FreezableParams",
    "ModelVersion",
    "ModelLifecycle",
    "LRUCache",
    "ModelCache",
    "APIServer",
    "RPCServer",
    "RPCClient",
    "AsyncPipeline",
    "AsyncTaskManager",
    "StreamProcessor",
    "ProgressCallback",
    "Plugin",
    "PluginManager",
    "PluginDependency",
    # 性能优化 (步骤66-80)
    "ObjectPool",
    "PoolContext",
    "PerformanceBatchProcessor",
    "MemoryPool",
    "MemoryBlock",
    "DelayedGC",
    "NLPThreadPoolExecutor",
    "ParallelTokenizer",
    "NLPProcessPoolExecutor",
    "GPUInterface",
    "BatchInference",
    "MixedPrecisionInference",
    "TensorRTInterface",
    "MemoryMappedFile",
    "DictionaryCompressor",
    "LRUResultCache",
    "PerformanceMonitor",
    "OptimizationSuite",
    "Metric",
    "DistributedTask",
    "SimpleTaskScheduler",
    # 企业级功能 (步骤81-85)
    "LogLevel",
    "LogFormat",
    "StructuredLogRecord",
    "ConsoleLogHandler",
    "FileLogHandler",
    "TimeRotatingFileLogHandler",
    "MemoryLogHandler",
    "LevelFilter",
    "KeywordFilter",
    "ModuleFilter",
    "Logger",
    "LogManager",
    "get_logger",
    "HealthStatus",
    "HealthCheck",
    "MemoryHealthCheck",
    "DiskHealthCheck",
    "HealthChecker",
    "MetricType",
    "PrometheusMetric",
    "PrometheusCounter",
    "PrometheusGauge",
    "PrometheusRegistry",
    "generate_dockerfile_content",
    "generate_k8s_deployment_content",
    "generate_k8s_service_content",
    "generate_k8s_ingress_content",
    # 企业级功能 (步骤86-90)
    "CircuitState",
    "RateLimitState",
    "TokenBucket",
    "SlidingWindow",
    "CircuitBreaker",
    "TokenType",
    "Permission",
    "EnterpriseToken",
    "AuthContext",
    "Authenticator",
    "Authorizer",
    "ConfigEvent",
    "ConfigWatch",
    "InMemoryConfigStore",
    "FileConfigStore",
    "ConfigManager",
    "DeploymentState",
    "TrafficRule",
    "DeploymentVersion",
    "CanaryDeployer",
    "BackupType",
    "ClusterNode",
    "FailoverStrategy",
    "DataBackupManager",
    "FailoverController",
    # 繁体中文支持
    "TraditionalChineseConverter",
    "TraditionalChineseDictionary",
]
