__version__ = "0.3.0-beta"
__codename__ = "coca"
__version_info__ = (0, 3, 0, "beta")

from .segmentor import Segmentor
from .dictionary import Dictionary, UserDictionary, DictionaryManager
from .domain_dictionary import DomainDictionary, DomainDictionaryManager
from .network_dictionary import NetworkDictionary
from .stopwords import StopWords
from .keyword_extractor import KeywordExtractor
from .similarity import Similarity
from .trie import Trie
from .benchmark import PerformanceBenchmark, BenchmarkResult, measure_time
from .batch_processor import BatchProcessor
from .hmm import HMMSegmentor, train_from_file
from .ngram import NGramModel, BigramModel, TrigramModel
from .crf import CRFModel, CRFSegmentor, CRFFeatureTemplate
from .perceptron import StructuredPerceptron, PerceptronSegmentor, PerceptronFeatureTemplate
from .lattice import Lattice, LatticeEdge, LatticeNode, LatticeBuilder, LatticeSegmentor, PathScorer
from .ambiguity import AmbiguityType, AmbiguityRegion, AmbiguityResult, AmbiguityDetector
from .new_word_detector import NewWordDetector, MutualInformation, EntropyCalculator
from .pos_tagger import POS_TAGS, DEFAULT_TAGS, HMMPOSTagger, CRFPOSTagger, train_pos_from_file
from .ner import (
    NER_ENTITY_TYPES,
    NER_TAGS,
    DEFAULT_NER_TAGS,
    Entity,
    NERFeatureTemplate,
    CRFNERModel,
    NERRecognizer,
    create_sample_ner_corpus,
    train_ner_from_file,
    NestedEntity,
    EntityHierarchy,
    NESTING_RULES,
    NestedNERRecognizer,
    create_nested_ner_corpus,
)
from .entity_linker import (
    KnowledgeEntity,
    LinkedEntity,
    KnowledgeBase,
    EntityNormalizer,
    EntityLinker,
    create_sample_knowledge_base,
    create_sample_normalizer,
)
from .dependency_parser import (
    Transition,
    DEPENDENCY_RELATIONS,
    DEFAULT_RELATIONS,
    DependencyArc,
    DependencyNode,
    DependencyTree,
    ParserState,
    ArcEagerOracle,
    DependencyFeatureExtractor,
    DependencyParser,
    create_sample_dependency_corpus,
    train_dependency_parser_from_file,
)
from .constituent_parser import (
    CONSTITUENT_LABELS,
    POS_LABELS,
    DEFAULT_NON_TERMINALS,
    DEFAULT_TERMINALS,
    GrammarRule,
    ConstituentNode,
    ConstituentTree,
    PCFG,
    CKYParser,
    ConstituentParser,
    create_sample_constituent_trees,
    train_constituent_parser_from_file,
)
from .hybrid import (
    HybridStrategy,
    SegmenterType,
    SegmenterResult,
    HybridConfig,
    FusionContext,
    FusionStrategy,
    VoteFusionStrategy,
    WeightedFusionStrategy,
    CascadeFusionStrategy,
    ConfidenceFusionStrategy,
    FusionStrategyFactory,
    ConfidenceEstimator,
    CoverageConfidenceEstimator,
    WordQualityConfidenceEstimator,
    SegmentationQualityConfidenceEstimator,
    CompositeConfidenceEstimator,
    TextClassifier,
    StrategySelector,
    DeepLearningInterface,
    HybridSegmentor,
)
from .scel_parser import ScelParser, ScelWord, ScelMetadata, ScelBatchParser
from .sogou_dict import ScelConverter, SogouDictionary, SogouDictionaryManager
from .managers import (
    DictionaryService,
    StopWordsManager,
    KeywordExtractorManager,
    SimilarityManager,
    MLSegmentorManager,
    LatticeSegmentorManager,
    AmbiguityDetectorManager,
    NewWordDetectorManager,
    HybridSegmentorManager,
)
from .thesaurus import (
    WordRelation,
    CATEGORY_NAMES,
    SUBCATEGORY_NAMES,
    ThesaurusEntry,
    SemanticCategory,
    Thesaurus,
    ThesaurusManager,
)
from .person_name import (
    Gender,
    SurnameType,
    Surname,
    NameChar,
    PersonName,
    NAME_CHAR_CATEGORIES,
    PersonNameDictionary,
    PersonNameManager,
)
from .location import (
    AdminLevel,
    Location,
    LocationDatabase,
    LocationManager,
)
from .organization import (
    OrgType,
    EnterpriseType,
    SchoolType,
    HospitalType,
    GovType,
    ENTERPRISE_SUFFIXES,
    SCHOOL_SUFFIXES,
    HOSPITAL_SUFFIXES,
    GOV_SUFFIXES,
    Organization,
    Enterprise,
    School,
    Hospital,
    Government,
    OrganizationDatabase,
    OrganizationManager,
)
from .terminology import (
    TermDomain,
    DOMAIN_SCEL_MAPPING,
    Term,
    TerminologyDatabase,
    TerminologyManager,
)

__all__ = [
    "Segmentor",
    "Dictionary",
    "UserDictionary",
    "DomainDictionary",
    "DomainDictionaryManager",
    "NetworkDictionary",
    "DictionaryManager",
    "StopWords",
    "KeywordExtractor",
    "Similarity",
    "Trie",
    "PerformanceBenchmark",
    "BenchmarkResult",
    "measure_time",
    "BatchProcessor",
    "HMMSegmentor",
    "train_from_file",
    "NGramModel",
    "BigramModel",
    "TrigramModel",
    "CRFModel",
    "CRFSegmentor",
    "CRFFeatureTemplate",
    "StructuredPerceptron",
    "PerceptronSegmentor",
    "PerceptronFeatureTemplate",
    "Lattice",
    "LatticeEdge",
    "LatticeNode",
    "LatticeBuilder",
    "LatticeSegmentor",
    "PathScorer",
    "AmbiguityType",
    "AmbiguityRegion",
    "AmbiguityResult",
    "AmbiguityDetector",
    "NewWordDetector",
    "MutualInformation",
    "EntropyCalculator",
    "POS_TAGS",
    "DEFAULT_TAGS",
    "HMMPOSTagger",
    "CRFPOSTagger",
    "train_pos_from_file",
    "NER_ENTITY_TYPES",
    "NER_TAGS",
    "DEFAULT_NER_TAGS",
    "Entity",
    "NERFeatureTemplate",
    "CRFNERModel",
    "NERRecognizer",
    "create_sample_ner_corpus",
    "train_ner_from_file",
    "NestedEntity",
    "EntityHierarchy",
    "NESTING_RULES",
    "NestedNERRecognizer",
    "create_nested_ner_corpus",
    "KnowledgeEntity",
    "LinkedEntity",
    "KnowledgeBase",
    "EntityNormalizer",
    "EntityLinker",
    "create_sample_knowledge_base",
    "create_sample_normalizer",
    "Transition",
    "DEPENDENCY_RELATIONS",
    "DEFAULT_RELATIONS",
    "DependencyArc",
    "DependencyNode",
    "DependencyTree",
    "ParserState",
    "ArcEagerOracle",
    "DependencyFeatureExtractor",
    "DependencyParser",
    "create_sample_dependency_corpus",
    "train_dependency_parser_from_file",
    "CONSTITUENT_LABELS",
    "POS_LABELS",
    "DEFAULT_NON_TERMINALS",
    "DEFAULT_TERMINALS",
    "GrammarRule",
    "ConstituentNode",
    "ConstituentTree",
    "PCFG",
    "CKYParser",
    "ConstituentParser",
    "create_sample_constituent_trees",
    "train_constituent_parser_from_file",
    "HybridStrategy",
    "SegmenterType",
    "SegmenterResult",
    "HybridConfig",
    "FusionContext",
    "FusionStrategy",
    "VoteFusionStrategy",
    "WeightedFusionStrategy",
    "CascadeFusionStrategy",
    "AdaptiveFusionStrategy",
    "ConfidenceFusionStrategy",
    "FusionStrategyFactory",
    "ConfidenceEstimator",
    "CoverageConfidenceEstimator",
    "WordQualityConfidenceEstimator",
    "SegmentationQualityConfidenceEstimator",
    "CompositeConfidenceEstimator",
    "TextClassifier",
    "StrategySelector",
    "DeepLearningInterface",
    "HybridSegmentor",
    "ScelParser",
    "ScelWord",
    "ScelMetadata",
    "ScelBatchParser",
    "ScelConverter",
    "SogouDictionary",
    "SogouDictionaryManager",
    "DictionaryService",
    "StopWordsManager",
    "KeywordExtractorManager",
    "SimilarityManager",
    "MLSegmentorManager",
    "LatticeSegmentorManager",
    "AmbiguityDetectorManager",
    "NewWordDetectorManager",
    "HybridSegmentorManager",
    "WordRelation",
    "CATEGORY_NAMES",
    "SUBCATEGORY_NAMES",
    "ThesaurusEntry",
    "SemanticCategory",
    "Thesaurus",
    "ThesaurusManager",
    "Gender",
    "SurnameType",
    "Surname",
    "NameChar",
    "PersonName",
    "NAME_CHAR_CATEGORIES",
    "PersonNameDictionary",
    "PersonNameManager",
    "AdminLevel",
    "Location",
    "LocationDatabase",
    "LocationManager",
    "OrgType",
    "EnterpriseType",
    "SchoolType",
    "HospitalType",
    "GovType",
    "ENTERPRISE_SUFFIXES",
    "SCHOOL_SUFFIXES",
    "HOSPITAL_SUFFIXES",
    "GOV_SUFFIXES",
    "Organization",
    "Enterprise",
    "School",
    "Hospital",
    "Government",
    "OrganizationDatabase",
    "OrganizationManager",
    "TermDomain",
    "DOMAIN_SCEL_MAPPING",
    "Term",
    "TerminologyDatabase",
    "TerminologyManager",
]
